[package]
name = "neoq"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "*"
sha2 = "*"
tracing = "*"
thiserror = "*"
chrono = { version = "*", features = ["serde"] }
neo4rs = { git = "https://github.com/neo4j-labs/neo4rs", branch = "main", features = [
    "json",
    "uuid",
] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
