[package]
name = "neoq"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "*"
sha2 = "*"
tracing = "*"
thiserror = "*"
chrono = { version = "*", features = ["serde"] }
neo4rs = { version = "0.9.0-rc.9", features = ["json", "uuid"] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
